apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-s0wl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-s0wl
    app.kubernetes.io/part-of: tkwch-fix-0075-0058-app
  name: devfile-sample-s0wl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-s0wl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-s0wl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0058-tenant/tkwch-fix-0075-0058-app/devfile-sample-s0wl@sha256:c46626bd833ab7541012f1ea9774af0bc9fee1b7bb409165ebfaab328d208535
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
